version: '3'
services:
  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: develop
    volumes:
      - ./:/src
      # - ./docker/mlflow/tmp:/src/venv
    working_dir: "/src"
    tty: true
    ports: 
      - "5000:5000"
    restart: always
